const dadosDespesas = {
  despesas: [
    {
      id: '1',
      nome: 'Compras no mercado',
      valor: '300',
      descricao: 'Compras para a semana',
      tipo: 'Despesa do mes',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '2',
      nome: 'Compras no mercado',
      valor: '400',
      descricao: 'Compras para a semana',
      tipo: 'Despesa do mes',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '3',
      nome: 'Compras na feira',
      valor: '150',
      descricao: 'Compras para a semana',
      tipo: 'Despesa do mes',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '4',
      nome: 'Compras na feira',
      valor: '200',
      descricao: 'Compras para a semana',
      tipo: 'Despesa do mes',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '5',
      nome: 'Plano de celular',
      valor: '50',
      descricao: 'Oferecido pela operadora claro',
      tipo: 'Despesa fixa',
    },
    {
      id: '6',
      nome: 'Plano de Internet',
      valor: '150',
      descricao: 'Oferecido pela empresa Vivo',
      tipo: 'Despesa fixa',
    },
    {
      id: '7',
      nome: 'Plano de saude',
      valor: '350',
      descricao: 'Plano de saude provido pela empresa Unimed',
      tipo: 'Despesa fixa',
    },
    {
      id: '8',
      nome: 'Aluguel da casa',
      valor: '600',
      descricao: 'Aluguel da casa no bairo xxx',
      tipo: 'Despesa fixa',
    },
    {
      id: '9',
      nome: 'Roupas',
      valor: '100',
      descricao: 'Roupas para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '1/5',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '10',
      nome: 'Roupas',
      valor: '100',
      descricao: 'Roupas para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '2/5',
      vencimento: '2022-12-21T14:17:52.583Z',
    },
    {
      id: '11',
      nome: 'Roupas',
      valor: '100',
      descricao: 'Roupas para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '3/5',
      vencimento: '2023-1-21T14:17:52.583Z',
    },
    {
      id: '12',
      nome: 'Roupas',
      valor: '100',
      descricao: 'Roupas para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '4/5',
      vencimento: '2023-2-21T14:17:52.583Z',
    },
    {
      id: '13',
      nome: 'Roupas',
      valor: '100',
      descricao: 'Roupas para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '5/5',
      vencimento: '2023-3-21T14:17:52.583Z',
    },
    {
      id: '14',
      nome: 'Sapatos',
      valor: '40',
      descricao: 'Sapatos para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '1/2',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '15',
      nome: 'Sapatos',
      valor: '40',
      descricao: 'Sapatos para ir em um casamento',
      tipo: 'Despesa parcelada',
      qtdParcelas: '2/2',
      vencimento: '2022-12-21T14:17:52.583Z',
    },
    {
      id: '16',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '1/8',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '17',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '2/8',
      vencimento: '2022-12-21T14:17:52.583Z',
    },
    {
      id: '18',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '3/8',
      vencimento: '2023-1-21T14:17:52.583Z',
    },
    {
      id: '19',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '4/8',
      vencimento: '2023-2-21T14:17:52.583Z',
    },
    {
      id: '20',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '5/8',
      vencimento: '2023-3-21T14:17:52.583Z',
    },
    {
      id: '21',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '6/8',
      vencimento: '2023-4-21T14:17:52.583Z',
    },
    {
      id: '22',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '7/8',
      vencimento: '2023-5-21T14:17:52.583Z',
    },
    {
      id: '23',
      nome: 'iphone 13 pro max',
      valor: '300',
      descricao: 'Novo modelo de celular',
      tipo: 'Despesa parcelada',
      qtdParcelas: '8/8',
      vencimento: '2023-6-21T14:17:52.583Z',
    },
    {
      id: '24',
      nome: 'Presente de aniversario',
      valor: '100',
      descricao: 'Presente de aniversario para minha irma',
      tipo: 'Despesa parcelada',
      qtdParcelas: '1/3',
      vencimento: '2022-11-21T14:17:52.583Z',
    },
    {
      id: '25',
      nome: 'Presente de aniversario',
      valor: '100',
      descricao: 'Presente de aniversario para minha irma',
      tipo: 'Despesa parcelada',
      qtdParcelas: '2/3',
      vencimento: '2022-12-21T14:17:52.583Z',
    },
    {
      id: '26',
      nome: 'Presente de aniversario',
      valor: '100',
      descricao: 'Presente de aniversario para minha irma',
      tipo: 'Despesa parcelada',
      qtdParcelas: '3/3',
      vencimento: '2023-1-21T14:17:52.583Z',
    },
  ],
};
export default dadosDespesas;
